# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'PinguMerchant' do

pod 'ObjectiveDDP', :path => '../ObjectiveDDP/ObjectiveDDP.podspec'
pod 'CDZQRScanningViewController'


end

target 'PinguMerchantTests' do

end

target 'PinguMerchantUITests' do

end

