# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'PinguPay' do

pod 'ObjectiveDDP', :path => '../ObjectiveDDP/ObjectiveDDP.podspec'
pod 'CDZQRScanningViewController'

end

target 'PinguPayTests' do

end

target 'PinguPayUITests' do

end

